apiVersion: apps/v1
kind: Deployment
metadata:
  name: html
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
      - name: html
        image: kishoren27/my-html-app
        ports:
        - containerPort: 80
